### ISSUE TITLE
Thumbnails redirect to https://www.google.com/false

### ISSUE THREAD

**Issue by zevelorgani** [Lorentz83/userscripts#5]
https://greasyfork.org/en/forum/discussion/8920/bug

**Comment by Lorentz83** [comment]
Fixed in the version 7.0
Most of the code has been rewritten to be faster and simpler to maintain and a lot of dead code useful for older versions (mostly basic search) has been deleted;
Some features (like the direct links from the google web search) are currently missing. They will be reintroduced, but feel free to fill a bugreport if you think I forgot them.

**Comment by zevelorgani** [comment]
Does the script auto-update?

**Comment by Lorentz83** [comment]
It should if you didn't change it. 
By the way, in firefox you can force the update doing: menu, add-ons, user scripts, right click on "find updates" or "force find updates". 
If both are disabled just delete and reinstall it.
